# Generated by Django 4.1.2 on 2022-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=20)),
                ('cpu_manufacturer', models.CharField(max_length=20)),
                ('cpu_architecture', models.CharField(max_length=20)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_threads', models.IntegerField()),
                ('cpu_clock', models.FloatField()),
                ('cpu_turbo', models.FloatField()),
                ('cpu_tdp', models.IntegerField()),
            ],
        ),
    ]
